version: "3.9"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lab1
    ports:
      - "3306:3306"
  bank2:
    image: jacarandap/bank2
    environment:
      - MYSQL_HOST=mysql
      - RISK_HOST=riskassesment
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  riskassesment:
    image: daneidmark/risk:0.0.1
    environment:
      - SERVER_PORT=8085
    ports:
      - "8085:8085"